checks:
    javascript: true

build:
    environment:
        node: v16.20.2

    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run

        # tests: true
